"""Export a session as an AI-ready tuning report (Markdown) or lap CSV.

The Markdown export is designed to be pasted straight into Claude or ChatGPT:
compact tables, explicit units, the tuning verdicts this tool computed, a
fill-in section for the player's current setup (telemetry cannot see spring
rates or pressures), and a prompt that tells the model exactly what to do
with all of it.
"""

from __future__ import annotations

import csv
import io
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from .laps import WHEELS, lap_report
from .session_data import SessionData

# Display maps (presentation only — raw ints always shown too). Class letters
# follow the FH5-era Data Out convention; unverified for FH6, so exports show
# both letter and raw int.
CAR_CLASS = {0: "D", 1: "C", 2: "B", 3: "A", 4: "S1", 5: "S2", 6: "X"}
DRIVETRAIN = {0: "FWD", 1: "RWD", 2: "AWD"}

AI_PROMPT = """\
You are an experienced Forza Horizon tuner. Above is telemetry from my
session, exported by the open-source FH6 telemetry tool, plus my current
setup values where I've filled them in.

Work through it in this order:
1. Read the balance verdict, understeer index (positive = understeer,
   negative = oversteer), and front/rear slide times. Diagnose the car's
   dominant handling problem, citing the specific numbers.
2. Check tyre temperatures against the working window shown. Cold = not
   enough load/camber/pressure too high for that axle; hot = overworked axle
   (too much roll stiffness there, pressure too low, or driving style).
   Front-vs-rear delta indicates which end is doing the work.
3. Check traction events (wheelspin, brake lock) against drivetrain type,
   and suspension travel / bottom-out counts for spring & ride-height issues.
4. Check gearing: time on limiter and average shift RPM.
5. Propose specific setup changes, most impactful first. For each: the
   setting, direction and rough magnitude, and which telemetry number
   justifies it. Stay within what Forza's tuning screen exposes (tyre
   pressure, gearing, camber/toe/caster, anti-roll bars, springs, ride
   height, damping, aero, diff, brake balance/pressure).
6. If my setup values are missing for a setting you want to change, say what
   to look at in-game and give your best directional advice anyway.
7. Finish with the single highest-priority change and what I should feel
   from the driver's seat if it works.
"""


def _fmt_lap_time(seconds: Optional[float]) -> str:
    if not seconds or seconds <= 0:
        return "–"
    m = int(seconds // 60)
    s = seconds - m * 60
    return f"{m}:{s:06.3f}"


def _md_table(headers: List[str], rows: List[List[Any]]) -> str:
    out = ["| " + " | ".join(headers) + " |",
           "| " + " | ".join("---" for _ in headers) + " |"]
    for row in rows:
        out.append("| " + " | ".join(str(c) for c in row) + " |")
    return "\n".join(out)


def build_markdown(sd: SessionData, meta: Dict[str, Any], version: str) -> str:
    """Render the full tuning report for one session."""
    rep = lap_report(sd)
    session = rep["session"] or {}
    verdicts = rep["verdicts"] or {}
    balance = verdicts.get("balance", {})
    temps = verdicts.get("tyre_temps", {})

    cls_raw = meta.get("car_class")
    cls = CAR_CLASS.get(cls_raw, "?") if cls_raw is not None else "?"
    dt_raw = meta.get("drivetrain")
    drivetrain = DRIVETRAIN.get(dt_raw, "?") if dt_raw is not None else "?"
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: List[str] = []
    add = lines.append

    add(f"# Forza Horizon 6 tuning report — {meta.get('name', 'session')}")
    add("")
    add(f"Generated by [Forza-6-telemetry](https://github.com/ClickClickMedia/Forza-6-telemetry) "
        f"v{version} on {generated}. Telemetry units: temps °C (converted "
        f"from the game's °F), speed km/h, slip channels normalized "
        f"(1.0 = grip limit), suspension travel normalised 0–1.")
    add("")

    add("## Car")
    add("")
    add(f"- Car ordinal: **{meta.get('car_ordinal', '?')}** "
        f"*(replace with the actual car name + your build, e.g. engine/aspiration swaps)*")
    add(f"- Class: **{cls}** (raw {cls_raw}) · PI **{meta.get('car_pi', '?')}**")
    add(f"- Drivetrain: **{drivetrain}** · Cylinders: {meta.get('cylinders', '?')}")
    add("")

    add("## Session")
    add("")
    add(f"- Recorded: {meta.get('created_at', '?')}")
    add(f"- Duration: {session.get('duration_s', 0):.0f} s · "
        f"Distance: {session.get('distance_m', 0) / 1000:.2f} km")
    best = rep.get("best_lap_s")
    n_complete = sum(1 for l in rep["laps"] if l.get("complete"))
    if rep["has_laps"]:
        add(f"- Laps completed: {n_complete} · Best lap: **{_fmt_lap_time(best)}**")
    else:
        add("- Free roam / point-to-point (no lap markers in this session)")
    add(f"- Max speed: {session.get('speed', {}).get('max_kmh', 0):.0f} km/h · "
        f"Max lateral: {session.get('max_lat_g', 0):.2f} g")
    notes = (meta.get("notes") or "").strip()
    if notes:
        add(f"- Driver notes: {notes}")
    add("")

    add("## Tyres")
    add("")
    tyres = session.get("tyres_c", {})
    add(_md_table(
        ["Tyre", "Avg °C", "Max °C"],
        [[w, tyres.get(w, {}).get("avg", "–"), tyres.get(w, {}).get("max", "–")]
         for w in WHEELS],
    ))
    add("")
    window = temps.get("window_c", [60, 105])
    add(f"- Working window used for verdicts: {window[0]:.0f}–{window[1]:.0f} °C "
        f"(one sensor per tyre — Forza exposes no inner/middle/outer split)")
    front = temps.get("front", {})
    rear = temps.get("rear", {})
    add(f"- Front axle avg **{front.get('avg_c', '?')} °C** → {front.get('verdict', '?')} · "
        f"Rear axle avg **{rear.get('avg_c', '?')} °C** → {rear.get('verdict', '?')}")
    add(f"- Front−rear delta: **{session.get('temp_fr_delta_c', 0):+.1f} °C** "
        f"(negative = rears working harder)")
    add("")

    add("## Balance & traction")
    add("")
    add(f"- Balance verdict: **{balance.get('verdict', '?')}** · "
        f"understeer index {balance.get('understeer_index', 0):+.3f} "
        f"(mean normalized |front slip angle| − |rear|, cornering on grip; "
        f"front axle ran {balance.get('front_slip_angle_corner_avg', 0):.2f} "
        f"of grip limit, rear {balance.get('rear_slip_angle_corner_avg', 0):.2f})")
    if balance.get("caveat"):
        add(f"- ⚠ {balance['caveat']} "
            f"(drift/opposite-lock time: {balance.get('pct_drifting', 0):.0f} % of session)")
    add(f"- Slide time beyond combined-slip 1.0: front {balance.get('front_slide_time_s', 0):.1f} s · "
        f"rear {balance.get('rear_slide_time_s', 0):.1f} s")
    trac = session.get("traction", {})
    add(f"- Wheelspin events: {trac.get('wheelspin_events', 0)} · "
        f"Brake-lock events: {trac.get('brake_lock_events', 0)}")
    inputs = session.get("inputs", {})
    add(f"- Full throttle: {inputs.get('pct_full_throttle', 0):.1f} % of session · "
        f"Braking: {inputs.get('pct_braking', 0):.1f} %")
    add("")

    add("## Suspension (normalised travel, 0 = full extension, 1 = bottomed)")
    add("")
    susp = session.get("suspension", {})
    add(_md_table(
        ["Corner", "Avg", "Max"],
        [[w, susp.get(w, {}).get("avg", "–"), susp.get(w, {}).get("max", "–")]
         for w in WHEELS],
    ))
    add("")
    add(f"- Bottom-out events (any corner ≥ 0.98): "
        f"{session.get('suspension_bottom_out_events', 0)}")
    add("")

    add("## Gearing")
    add("")
    g = session.get("gearing", {})
    add(f"- Top gear used: {g.get('top_gear', '?')} · "
        f"Upshifts: {g.get('shift_count', 0)} · "
        f"Avg shift RPM: {g.get('shift_rpm_avg') or '–'}")
    add(f"- Time on limiter (≥97% max RPM): {g.get('pct_on_limiter', 0):.1f} %")
    add("")

    if rep["has_laps"] and rep["laps"]:
        add("## Laps")
        add("")
        rows = []
        for l in rep["laps"]:
            rows.append([
                l["lap"] if l["lap"] is not None else "–",
                _fmt_lap_time(l.get("time_s")) + ("" if l.get("complete") else " *(partial)*"),
                f"{l['speed']['avg_kmh']:.0f}",
                f"{l['speed']['max_kmh']:.0f}",
                f"{l['inputs']['pct_full_throttle']:.0f}",
                f"{l['inputs']['pct_braking']:.0f}",
                f"{l['balance']['understeer_index']:+.3f}",
                f"{l['temp_fr_delta_c']:+.1f}",
            ])
        add(_md_table(
            ["Lap", "Time", "Avg km/h", "Max km/h", "Full-thr %", "Brake %",
             "USI", "F−R °C"],
            rows,
        ))
        add("")

    add("## My current setup (fill in before asking the AI)")
    add("")
    add("```")
    add("Tyre pressure  F: ___ psi   R: ___ psi")
    add("Gearing        final: ___   (per-gear if custom)")
    add("Camber         F: ___°      R: ___°")
    add("Toe            F: ___°      R: ___°")
    add("Caster         ___°")
    add("Anti-roll bars F: ___       R: ___")
    add("Springs        F: ___       R: ___   Ride height F/R: ___ / ___")
    add("Damping rebound F/R: ___ / ___   bump F/R: ___ / ___")
    add("Aero           F: ___       R: ___")
    add("Differential   accel/decel: ___ / ___  (centre balance if AWD)")
    add("Brakes         balance: ___  pressure: ___")
    add("What I want    e.g. \"less mid-corner understeer, keep exit traction\"")
    add("```")
    add("")

    add("## Prompt for the AI")
    add("")
    add(AI_PROMPT)
    return "\n".join(lines)


# --- Per-lap CSV -----------------------------------------------------------
_LAP_CSV_HEADER = [
    "lap", "complete", "time_s", "duration_s", "distance_m",
    "avg_kmh", "max_kmh", "pct_full_throttle", "pct_braking",
    "understeer_index", "front_slide_time_s", "rear_slide_time_s",
    "wheelspin_events", "brake_lock_events",
    "temp_fl_avg_c", "temp_fr_avg_c", "temp_rl_avg_c", "temp_rr_avg_c",
    "temp_front_avg_c", "temp_rear_avg_c", "temp_fr_delta_c",
    "susp_fl_max", "susp_fr_max", "susp_rl_max", "susp_rr_max",
    "bottom_out_events", "top_gear", "shift_rpm_avg", "pct_on_limiter",
    "max_lat_g",
]


def build_laps_csv(sd: SessionData) -> str:
    rep = lap_report(sd)
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(_LAP_CSV_HEADER)
    for l in rep["laps"]:
        t = l.get("tyres_c", {})
        s = l.get("suspension", {})
        writer.writerow([
            l.get("lap"), int(bool(l.get("complete"))), l.get("time_s"),
            l.get("duration_s"), l.get("distance_m"),
            l["speed"]["avg_kmh"], l["speed"]["max_kmh"],
            l["inputs"]["pct_full_throttle"], l["inputs"]["pct_braking"],
            l["balance"]["understeer_index"],
            l["balance"]["front_slide_time_s"],
            l["balance"]["rear_slide_time_s"],
            l["traction"]["wheelspin_events"],
            l["traction"]["brake_lock_events"],
            t.get("FL", {}).get("avg"), t.get("FR", {}).get("avg"),
            t.get("RL", {}).get("avg"), t.get("RR", {}).get("avg"),
            l.get("temp_front_avg_c"), l.get("temp_rear_avg_c"),
            l.get("temp_fr_delta_c"),
            s.get("FL", {}).get("max"), s.get("FR", {}).get("max"),
            s.get("RL", {}).get("max"), s.get("RR", {}).get("max"),
            l.get("suspension_bottom_out_events"),
            l["gearing"]["top_gear"], l["gearing"]["shift_rpm_avg"],
            l["gearing"]["pct_on_limiter"],
            l.get("max_lat_g"),
        ])
    return buf.getvalue()
